# Generated by Django 4.2.3 on 2023-07-10 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('start_time', models.CharField(blank=True, max_length=25, null=True)),
                ('end_time', models.CharField(blank=True, max_length=25, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doc_image')),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.BooleanField(blank=True, default=False, null=True)),
                ('monday', models.BooleanField(blank=True, default=False, null=True)),
                ('tuesday', models.BooleanField(blank=True, default=False, null=True)),
                ('wednesday', models.BooleanField(blank=True, default=False, null=True)),
                ('thursday', models.BooleanField(blank=True, default=False, null=True)),
                ('friday', models.BooleanField(blank=True, default=False, null=True)),
                ('saturday', models.BooleanField(blank=True, default=False, null=True)),
                ('doc_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docdays', to='backend_api.doctor')),
            ],
        ),
    ]
