# Generated by Django 4.2.3 on 2023-07-14 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('civilid', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=500)),
                ('sch_date', models.CharField(max_length=50)),
                ('sch_time', models.CharField(max_length=50)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='backend_api.doctor')),
                ('user_cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
