# Generated by Django 4.2.3 on 2023-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, default='ongoing', max_length=50, null=True),
        ),
    ]
