# Generated by Django 4.2.3 on 2023-07-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_results_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('List_date', models.TextField(blank=True, null=True)),
                ('List_day', models.TextField(blank=True, null=True)),
                ('List_time', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
